export const countryData: Record<
  string,
  {
    name: string
    code: string
    flag: string
    format: string
    example: string
    maxDigits: number
  }
> = {
  US: {
    name: "United States",
    code: "1",
    flag: "🇺🇸",
    format: "###-###-####",
    example: "555-123-4567",
    maxDigits: 10,
  },
  GB: {
    name: "United Kingdom",
    code: "44",
    flag: "🇬🇧",
    format: "#### ######",
    example: "7911 123456",
    maxDigits: 10,
  },
  IN: {
    name: "India",
    code: "91",
    flag: "🇮🇳",
    format: "##### #####",
    example: "98765 43210",
    maxDigits: 10,
  },
  CA: {
    name: "Canada",
    code: "1",
    flag: "🇨🇦",
    format: "###-###-####",
    example: "416-123-4567",
    maxDigits: 10,
  },
  AU: {
    name: "Australia",
    code: "61",
    flag: "🇦🇺",
    format: "### ### ###",
    example: "412 345 678",
    maxDigits: 9,
  },
  DE: {
    name: "Germany",
    code: "49",
    flag: "🇩🇪",
    format: "### #######",
    example: "170 1234567",
    maxDigits: 11,
  },
  FR: {
    name: "France",
    code: "33",
    flag: "🇫🇷",
    format: "# ## ## ## ##",
    example: "6 12 34 56 78",
    maxDigits: 9,
  },
  JP: {
    name: "Japan",
    code: "81",
    flag: "🇯🇵",
    format: "##-####-####",
    example: "90-1234-5678",
    maxDigits: 10,
  },
  CN: {
    name: "China",
    code: "86",
    flag: "🇨🇳",
    format: "### #### ####",
    example: "139 1234 5678",
    maxDigits: 11,
  },
  BR: {
    name: "Brazil",
    code: "55",
    flag: "🇧🇷",
    format: "## #####-####",
    example: "11 98765-4321",
    maxDigits: 11,
  },
  RU: {
    name: "Russia",
    code: "7",
    flag: "🇷🇺",
    format: "### ###-##-##",
    example: "912 345-67-89",
    maxDigits: 10,
  },
  MX: {
    name: "Mexico",
    code: "52",
    flag: "🇲🇽",
    format: "## ## ####-####",
    example: "55 12 3456-7890",
    maxDigits: 10,
  },
  IT: {
    name: "Italy",
    code: "39",
    flag: "🇮🇹",
    format: "### ######",
    example: "345 1234567",
    maxDigits: 10,
  },
  ES: {
    name: "Spain",
    code: "34",
    flag: "🇪🇸",
    format: "### ### ###",
    example: "612 345 678",
    maxDigits: 9,
  },
  KR: {
    name: "South Korea",
    code: "82",
    flag: "🇰🇷",
    format: "##-####-####",
    example: "10-1234-5678",
    maxDigits: 10,
  },
  NL: {
    name: "Netherlands",
    code: "31",
    flag: "🇳🇱",
    format: "# ########",
    example: "6 12345678",
    maxDigits: 9,
  },
  TR: {
    name: "Turkey",
    code: "90",
    flag: "🇹🇷",
    format: "### ### ####",
    example: "532 123 4567",
    maxDigits: 10,
  },
  SA: {
    name: "Saudi Arabia",
    code: "966",
    flag: "🇸🇦",
    format: "## ### ####",
    example: "50 123 4567",
    maxDigits: 9,
  },
  ZA: {
    name: "South Africa",
    code: "27",
    flag: "🇿🇦",
    format: "## ### ####",
    example: "71 234 5678",
    maxDigits: 9,
  },
  SG: {
    name: "Singapore",
    code: "65",
    flag: "🇸🇬",
    format: "#### ####",
    example: "8123 4567",
    maxDigits: 8,
  },
  AE: {
    name: "United Arab Emirates",
    code: "971",
    flag: "🇦🇪",
    format: "## ### ####",
    example: "50 123 4567",
    maxDigits: 9,
  },
  NG: {
    name: "Nigeria",
    code: "234",
    flag: "🇳🇬",
    format: "### ### ####",
    example: "803 123 4567",
    maxDigits: 10,
  },
  EG: {
    name: "Egypt",
    code: "20",
    flag: "🇪🇬",
    format: "### ### ####",
    example: "100 123 4567",
    maxDigits: 10,
  },
  PH: {
    name: "Philippines",
    code: "63",
    flag: "🇵🇭",
    format: "### ### ####",
    example: "917 123 4567",
    maxDigits: 10,
  },
  MY: {
    name: "Malaysia",
    code: "60",
    flag: "🇲🇾",
    format: "##-### ####",
    example: "12-345 6789",
    maxDigits: 9,
  },
  TH: {
    name: "Thailand",
    code: "66",
    flag: "🇹🇭",
    format: "# #### ####",
    example: "8 1234 5678",
    maxDigits: 9,
  },
  ID: {
    name: "Indonesia",
    code: "62",
    flag: "🇮🇩",
    format: "###-###-####",
    example: "812-345-6789",
    maxDigits: 10,
  },
  VN: {
    name: "Vietnam",
    code: "84",
    flag: "🇻🇳",
    format: "### ### ####",
    example: "912 345 678",
    maxDigits: 9,
  },
  AR: {
    name: "Argentina",
    code: "54",
    flag: "🇦🇷",
    format: "## ####-####",
    example: "11 1234-5678",
    maxDigits: 10,
  },
  AT: {
    name: "Austria",
    code: "43",
    flag: "🇦🇹",
    format: "### ######",
    example: "664 1234567",
    maxDigits: 10,
  },
  BD: {
    name: "Bangladesh",
    code: "880",
    flag: "🇧🇩",
    format: "####-######",
    example: "1711-123456",
    maxDigits: 10,
  },
  BE: {
    name: "Belgium",
    code: "32",
    flag: "🇧🇪",
    format: "### ## ## ##",
    example: "470 12 34 56",
    maxDigits: 9,
  },
  CL: {
    name: "Chile",
    code: "56",
    flag: "🇨🇱",
    format: "# #### ####",
    example: "9 1234 5678",
    maxDigits: 9,
  },
  CO: {
    name: "Colombia",
    code: "57",
    flag: "🇨🇴",
    format: "### ### ####",
    example: "320 123 4567",
    maxDigits: 10,
  },
  DK: {
    name: "Denmark",
    code: "45",
    flag: "🇩🇰",
    format: "## ## ## ##",
    example: "20 12 34 56",
    maxDigits: 8,
  },
  FI: {
    name: "Finland",
    code: "358",
    flag: "🇫🇮",
    format: "## ### ####",
    example: "40 123 4567",
    maxDigits: 9,
  },
  GR: {
    name: "Greece",
    code: "30",
    flag: "🇬🇷",
    format: "### ### ####",
    example: "697 123 4567",
    maxDigits: 10,
  },
  HK: {
    name: "Hong Kong",
    code: "852",
    flag: "🇭🇰",
    format: "#### ####",
    example: "9123 4567",
    maxDigits: 8,
  },
  HU: {
    name: "Hungary",
    code: "36",
    flag: "🇭🇺",
    format: "## ### ####",
    example: "30 123 4567",
    maxDigits: 9,
  },
  IE: {
    name: "Ireland",
    code: "353",
    flag: "🇮🇪",
    format: "## ### ####",
    example: "85 123 4567",
    maxDigits: 9,
  },
  IL: {
    name: "Israel",
    code: "972",
    flag: "🇮🇱",
    format: "##-###-####",
    example: "50-123-4567",
    maxDigits: 9,
  },
  NO: {
    name: "Norway",
    code: "47",
    flag: "🇳🇴",
    format: "### ## ###",
    example: "406 12 345",
    maxDigits: 8,
  },
  NZ: {
    name: "New Zealand",
    code: "64",
    flag: "🇳🇿",
    format: "## ### ####",
    example: "21 123 4567",
    maxDigits: 9,
  },
  PK: {
    name: "Pakistan",
    code: "92",
    flag: "🇵🇰",
    format: "### ### ####",
    example: "300 123 4567",
    maxDigits: 10,
  },
  PE: {
    name: "Peru",
    code: "51",
    flag: "🇵🇪",
    format: "### ### ###",
    example: "912 345 678",
    maxDigits: 9,
  },
  PL: {
    name: "Poland",
    code: "48",
    flag: "🇵🇱",
    format: "### ### ###",
    example: "512 345 678",
    maxDigits: 9,
  },
  PT: {
    name: "Portugal",
    code: "351",
    flag: "🇵🇹",
    format: "### ### ###",
    example: "912 345 678",
    maxDigits: 9,
  },
  RO: {
    name: "Romania",
    code: "40",
    flag: "🇷🇴",
    format: "### ### ###",
    example: "712 345 678",
    maxDigits: 9,
  },
  SE: {
    name: "Sweden",
    code: "46",
    flag: "🇸🇪",
    format: "##-### ## ##",
    example: "70-123 45 67",
    maxDigits: 9,
  },
  CH: {
    name: "Switzerland",
    code: "41",
    flag: "🇨🇭",
    format: "## ### ## ##",
    example: "78 123 45 67",
    maxDigits: 9,
  },
  TW: {
    name: "Taiwan",
    code: "886",
    flag: "🇹🇼",
    format: "### ### ###",
    example: "912 345 678",
    maxDigits: 9,
  },
  UA: {
    name: "Ukraine",
    code: "380",
    flag: "🇺🇦",
    format: "## ### ####",
    example: "50 123 4567",
    maxDigits: 9,
  },
}
